services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./default.json:/consul/config/default.json:ro
    networks:
      cab:

networks:
  cab:
    driver: bridge
